version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: first_backend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
